# Config JoinLeave Plugin

messages:
    join: "&8[&a+&8] &6{player}"
    leave: "&8[&c-&8] &6{player}"
    reload: "&7[&fJoinLeave&7] &aConfiguration reloaded successfully!"
    toggle_on: "&7[&fJoinLeave&7] &aJoin/Leave messages enabled"
    toggle_off: "&7[&fJoinLeave&7] &cJoin/Leave messages disabled"

settings:
    messages_enabled: true
